on: [pull_request, push]
jobs:
  checks:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install dependencies
        run: pacman -Syu --noconfirm make parallel wget cmake ninja verilator git llvm clang python autoconf automake
      - name: Test
        run: make test
