on: [pull_request, push]
jobs:
  checks:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm make mill z3 parallel wget cmake ninja dtc verilator git llvm clang lld protobuf antlr4 python autoconf automake
      - uses: actions/checkout@v2
      - name: Test
        run: make test
